# Generated by Django 3.2.18 on 2023-02-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(max_length=50, verbose_name='Описание')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('body', models.CharField(max_length=50, verbose_name='Тип кузова')),
            ],
        ),
    ]
