# Generated by Django 3.2.18 on 2023-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230215_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2010, verbose_name='Год выпуска'),
        ),
    ]
