# Generated by Django 3.2.18 on 2023-02-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
